In [33]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [34]:
# random functions to ease the work :
# calcul y_bar
def ybar(y):
    return y.mean()

# Sum of squared errors (SSE)
def sse(y_target,y_prediction):
    s = 0
    for i in range(len(y_target)): 
        s = s + ((y_target[i] - y_prediction[i])**2)
    return s

# Sum of residuals (SSr)
def ssr(y_bar,y_prediction):
    s = 0
    for i in range(len(y_prediction)): 
        s = s + ((y_prediction[i] - y_bar)**2)
    return s

# Sum of errors (SST)
def sst(y_target,y_bar):
    s = 0
    for i in range(len(y_target)): 
        s = s + ((y_target[i] - y_bar)**2)
    return s

# calcule y pred
def predictY(re, x):
    y_hat = []
    for i in range(x.shape[0]):
        line = re[0]
        for j in range(x.shape[1]):
            line = line + (re[j+1]*x[i][j])
        y_hat.append(line)
    return y_hat

# plot gradient descent cost
def plot_Cost(history):
    plt.plot(history)
    plt.xlabel('Iteration')
    plt.ylabel('Cost')
    plt.title('Gradient Descent - Cost History')
    plt.show()

# gradient_descent function in case a solution couldn't be found with closed-form method
def gradient_descent(X, y, learning_rate=0.01, num_iterations=20000):
    num_samples, num_features = X.shape
    theta = np.zeros(num_features)
    history = np.zeros((num_iterations, 1))
    for i in range(num_iterations):
        gradient = (1/num_samples) * (X.T.dot(X.dot(theta) - y))
        theta = theta - learning_rate * gradient
        cost = (1/(2*num_samples)) * np.sum((X.dot(theta) - y)**2)
        history[i] = cost
    return theta, history

# model
def MultiLinearRegression(x, y):
    # Add intercept term (a column with all ones)
    X = np.c_[np.ones(x.shape[0]), x]
    try:
        # in case you want to force-run the gradient_descent method, uncomment the next line 
        # fail = 4/0
        # Use closed-form solution:
        xt = X.T
        xt_x = xt.dot(X)
        xt_x_1 = np.linalg.inv(xt_x)
        xt_x_1_xt = xt_x_1.dot(xt)
        res = xt_x_1_xt.dot(y)
        print('using closed-form method : ')
        return res
    except : # Use gradient descent if closed-form solution fails
        theta, h = gradient_descent(X, y)
        plot_Cost(h) # this function plots the evolution of the cost of the gradient descent
        print('using gradient descent method : ')
        return theta

In [35]:
# importing data 
df = pd.read_csv('x1x2y_data.csv')
print(df)

# data separation and preparation 
X = df[['x1','x2']].to_numpy()
Y = df['y'].to_numpy()
print('x: ',X); print('y: ',Y);

   x1  x2   y
0   1   4   1
1   2   5   6
2   3   8   8
3   4   2  12
x:  [[1 4]
 [2 5]
 [3 8]
 [4 2]]
y:  [ 1  6  8 12]


In [36]:
# calling the model to learn
result = MultiLinearRegression(X, Y)
print('a: ',result)

using closed-form method : 
a:  [-1.69945355  3.48360656 -0.05464481]


In [47]:
# calculation of y_predict
yhat = predictY(result,X)
print(yhat)
print(Y)

[1.5655737704918067, 4.994535519125687, 8.314207650273229, 12.125683060109294]
[ 1  6  8 12]


In [48]:
# calculating SSE error :
print('sse: ',sse(Y,yhat))

sse:  1.4453551912568299


In [49]:
# testing with scikit-lea
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X,Y)
yhat__w_model = model.predict(X)
print(yhat__w_model)
print('sse: ',sse(Y,yhat__w_model))

[ 1.56557377  4.99453552  8.31420765 12.12568306]
sse:  1.4453551912568303


In [50]:
# importing data for second example
df2 = pd.read_csv('student_data.csv')

In [51]:
df2.drop('studentNum', axis=1, inplace=True)
df2

science_grade  chemistry_grade  hours_studied  y_act
0             60               80              5     82
1             70               75              7     94
2             50               55             10     45
3             40               56              7     43

In [52]:
# data separation and preparation 
X2 = df2.iloc[:, :-1].to_numpy()
print('x: ',X2)
Y2 = df2.iloc[:, -1].to_numpy()
print('y: ',Y2)

x:  [[60 80  5]
 [70 75  7]
 [50 55 10]
 [40 56  7]]
y:  [82 94 45 43]


In [53]:
# calling the model to learn
result2 = MultiLinearRegression(X2, Y2)
print('a: ',result2)

using closed-form method : 
a:  [47.06896552  2.19137931 -0.77586207 -6.89655172]


In [54]:
# calculation of y_predict
yhat2 = predictY(result2,X2)
print(yhat2)
print(Y2)

[81.99999999998641, 93.99999999998727, 44.99999999998474, 42.99999999998439]
[82 94 45 43]


In [55]:
# calculating SSE error :
print('sse: ',sse(Y2,yhat2))

sse:  8.2332950720970905e-22


In [56]:
# testing with scikit-lea
from sklearn.linear_model import LinearRegression
model2=LinearRegression()
model2.fit(X2,Y2)
yhat__w_model2 = model2.predict(X2)
print(yhat__w_model2)
print('sse: ',sse(Y2,yhat__w_model2))

[82. 94. 45. 43.]
sse:  2.0194839173657902e-27
